import {
  KEY_CUPS_BLOCK_1,
  KEY_CUPS_BLOCK_2,
  KEY_CUPS_BLOCK_3,
  KEY_CUPS_BLOCK_4,
  KEY_CUPS_BLOCK_5,
  KEY_CUPS_BLOCK_6,
  KEY_CUPS_BLOCK_7,
  KEY_CUPS_BLOCK_8,
  KEY_CUPS_BLOCK_9,
  KEY_CUPS_BLOCK_10,
} from 'constants/keyCups';
import React from 'react';
import { View } from 'react-native';
import { KeypadItem } from 'root';

import {
  KeyCupContainer,
  KeyCupContainerBottom,
  KeyCupContainerNumbers,
  KeyCupContainerTop,
  Wrapper,
} from './styles';
import type KeypadProps from './types';

function Keypad({ handleSetMathExpression }: KeypadProps): JSX.Element {
  return (
    <Wrapper>
      <KeyCupContainerTop>
        <KeypadItem
          data={KEY_CUPS_BLOCK_1}
          numCol={4}
          type="BASE"
          handleSetMathExpression={handleSetMathExpression}
          bgColor="#FFFFFF"
          textColor="#109DFF"
          radius="24"
          width="62"
          height="40"
          size="18"
        />
      </KeyCupContainerTop>
      <KeyCupContainer>
        <View>
          <KeyCupContainer>
            <KeypadItem
              data={KEY_CUPS_BLOCK_2}
              numCol={1}
              handleSetMathExpression={handleSetMathExpression}
              bgColor="#FFFFFF"
              textColor="#858585"
              radius="16"
              width="62"
              height="62"
              size="32"
              type="BASE"
            />
            <KeypadItem
              data={KEY_CUPS_BLOCK_3}
              numCol={1}
              handleSetMathExpression={handleSetMathExpression}
              bgColor="#FFFFFF"
              textColor="#858585"
              radius="16"
              width="62"
              height="62"
              size="22"
              type="BASE"
            />
            <KeypadItem
              data={KEY_CUPS_BLOCK_4}
              numCol={1}
              handleSetMathExpression={handleSetMathExpression}
              bgColor="#ADE2FF"
              textColor="#109DFF"
              radius="16"
              width="62"
              height="62"
              size="32"
              type="BASE"
            />
          </KeyCupContainer>
          <KeyCupContainerNumbers>
            <KeypadItem
              data={KEY_CUPS_BLOCK_5}
              numCol={3}
              handleSetMathExpression={handleSetMathExpression}
              bgColor="#FFFFFF"
              textColor="#38B9FF"
              radius="16"
              width="62"
              height="62"
              size="32"
              type="NUM"
            />
          </KeyCupContainerNumbers>
          <KeyCupContainerBottom>
            <View>
              <KeypadItem
                data={KEY_CUPS_BLOCK_9}
                numCol={1}
                handleSetMathExpression={handleSetMathExpression}
                bgColor="#FFFFFF"
                textColor="#109DFF"
                radius="16"
                width="144"
                height="60"
                size="32"
                type="BASE"
              />
            </View>
            <View>
              <KeypadItem
                data={KEY_CUPS_BLOCK_10}
                numCol={1}
                handleSetMathExpression={handleSetMathExpression}
                bgColor="#FFFFFF"
                textColor="#38B9FF"
                radius="16"
                width="62"
                height="62"
                size="32"
                type="BASE"
              />
            </View>
          </KeyCupContainerBottom>
        </View>
        <View>
          <View>
            <KeypadItem
              data={KEY_CUPS_BLOCK_6}
              handleSetMathExpression={handleSetMathExpression}
              bgColor="#ADE2FF"
              textColor="#109DFF"
              radius="16"
              width="62"
              height="64"
              size="32"
              type="FIRSTGROUP"
            />
          </View>
          <View>
            <KeypadItem
              data={KEY_CUPS_BLOCK_7}
              handleSetMathExpression={handleSetMathExpression}
              bgColor="#ADE2FF"
              textColor="#109DFF"
              radius="16"
              width="62"
              height="96"
              size="32"
              type="SECONDGROUP"
            />
            <KeypadItem
              data={KEY_CUPS_BLOCK_8}
              handleSetMathExpression={handleSetMathExpression}
              bgColor="#1991FF"
              textColor="#B2DAFF"
              radius="16"
              width="62"
              height="96"
              size="32"
              type="SECONDGROUP"
            />
          </View>
        </View>
      </KeyCupContainer>
    </Wrapper>
  );
}

export default Keypad;
